const shell = require('shelljs')

shell.exec('pnpm run build')
shell.cd('.vuepress/dist')
shell.exec('git init')
shell.exec('git add -A')
shell.exec('git commit -m "deploy"')
shell.exec('git push -f git@gitee.com:justorez/fe-performance-journey.git master:pages')
console.log('https://gitee.com/justorez/fe-performance-journey')
// shell.rm('-rf', '.git')
